"""fix_relationships

Revision ID: 52d96cb653d4
Revises: c40e6204af72
Create Date: 2026-01-15 12:56:56.246252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d96cb653d4'
down_revision: Union[str, Sequence[str], None] = 'c40e6204af72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'mailings', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mailings', type_='foreignkey')
    op.drop_column('mailings', 'owner_id')
    # ### end Alembic commands ###
